parameters:
    influxdb.url: 'http://localhost:8086'
    influxdb.token: ''
    influxdb.org: ''
    influxdb.bucket: ''
    influxdb.timeout: 30
    influxdb.verify_ssl: true
    influxdb.debug: false
    influxdb.precision: 'ns'
    
services:
    TimeSeriesPhp\Drivers\InfluxDB\InfluxDBDriver:
        arguments:
            $url: '%influxdb.url%'
            $token: '%influxdb.token%'
            $org: '%influxdb.org%'
            $bucket: '%influxdb.bucket%'
            $timeout: '%influxdb.timeout%'
            $verify_ssl: '%influxdb.verify_ssl%'
            $debug: '%influxdb.debug%'
            $precision: '%influxdb.precision%'
